name: rested_script
version: 0.1.0
description: >-
  A simple scripting made for the Rested Web Framework.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  string_tools:
    git: 
      url: https://github.com/thomasberge/string_tools
      ref: dev
repository: https://github.com/thomasberge/rested_script
